steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${_BRANCH_TAG}', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'push'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${_BRANCH_TAG}']
# Deploy image to Cloud Run Staging
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$_IMAGE_NAME-${_BRANCH_TAG}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${_BRANCH_TAG}'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--update-env-vars'
  - 'SHEET_ID=1OIUBp4kFxmpWJihhq6WLwJQR1Am4DsD59bEYlJZxeGY,TAB_ID=Database test [DO NOT DELETE],START_ROW=1,DB_NAME=entries-staging,PROJECT_ID=$PROJECT_ID,FLASK_ENV=development'
  waitFor: ['build', 'push']