steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'push'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME']
# Deploy image to Cloud Run Staging
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$_IMAGE_NAME-$BRANCH_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--update-env-vars'
  - 'CREATIVES_SHEET_HEADERS="name,location,city,state,field,links,gender,contact",CREATIVES_SHEET_ID=11xvRHdQomN6bBEJiBGbyKiEbTNikUQoLx0keaXx_MwU,CREATIVES_TAB_ID=Creatives/Writers Sheet,CREATIVES_START_ROW=3,CREATIVES_DB_NAME=creatives-staging,MUSIC_SHEET_ID=1OIUBp4kFxmpWJihhq6WLwJQR1Am4DsD59bEYlJZxeGY,MUSIC_TAB_ID=Original Sheet,MUSIC_START_ROW=5,MUSIC_DB_NAME=entries-staging,MUSIC_SHEET_HEADERS="name,country,city,state,type,link,genre,notes",PROJECT_ID=$PROJECT_ID,FLASK_ENV=development'
  waitFor: ['build', 'push']